name: img-cdn pipeline
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: golang check version
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go version


